### ISSUE TITLE
[HPC] [NWays] Add port conflicts in General Troubleshooting Section

### ISSUE THREAD

**Issue by keipertk** [gpuhackathons-org/gpubootcamp#12]
Suggestion to add a "General Troubleshooting" section to the top-level readme, for troubleshooting that applies to all the Docker images. Perhaps could move the 16GB GPU memory requirement there. 

And one additional troubleshooting item I'd like to see is for port conflicts when hosting multiple students running the workshop containers  on the same cluster. They will clobber each other on port 8888. So anyone hosting this workshop should be prepared to assign ports to students. Perhaps there there any other solutions you've encountered?

**Comment by bharatk-parallel** [comment]
Yes we could ideally add another section on the how to use in cluster env where multiple participants are using the material.

**Comment by bharatk-parallel** [comment]
Closing. Added to the README general troubleshooting. We plan to add additional README guides for the basics of container and multi-tenancy environment in the future as well. https://github.com/gpuhackathons-org/gpubootcamp/commit/00fcdff199ca24599d799853a62e02c0ab99c4d7
