### ISSUE TITLE
[HPC] [Nways] Adding Python langauge to HPC N-Ways tutorial

### ISSUE THREAD

**Issue by bharatk-parallel** [gpuhackathons-org/gpubootcamp#13]
Python is gaining traction in the HPC community and most sought-after programming language. The feature request is to add support of CUDA using CuPy and Numba for N-Ways tutorial.

- [x] Implementation of N-Ways MD with CuPy
- [x] Implementation of N-Ways MD with Numba

**Comment by programmah** [comment]
Pull request initiated

**Comment by programmah** [comment]
Python Pull request initiated

**Comment by programmah** [comment]
Merged pull request #40
