### ISSUE TITLE
[HPC] [NWays] Optimization for N-Ways with Nsight Compute

### ISSUE THREAD

**Issue by bharatk-parallel** [gpuhackathons-org/gpubootcamp#17]
Currently, the lab N-Ways covers the only introduction to OpenACC, OpenMP, CUDA, and ISO standards using Nsight System.
This feature request is to create material on optimization techniques with help of Nsight Compute for the above-given different methods

- [x] Optimization for OpenACC
- [x] Optimization for OpenMP
- [ ] Optimization CUDA

**Comment by mozhgan-kch** [comment]
Pull request #63 merged - this solves issue #17 (1 and 2)

**Comment by bharatk-parallel** [comment]
Closing the issue with OpenACC and OpenMP optimization. A new issue will be created to incorporate the cuda and restructuring for Nsight Compute.
