### ISSUE TITLE
[HPC] [N-Ways] Multi-GPU Programming

### ISSUE THREAD

**Issue by bharatk-parallel** [gpuhackathons-org/gpubootcamp#18]
All the training materials currently covers converting a sequential code to GPU using N-Ways. This feature request is to add bootcamp material related to Multi-GPU programming. Ideally the tutorial should cover different methods like
-- NVSHMEM
-- NCCL
-- MPI+X
Also the impact of system and network topology on scaling. The tutorial should also look into tools that help in getting more insights on scaling and bottlenecks.

**Comment by mozhgan-kch** [comment]
Reviews partly done : https://docs.google.com/document/d/1RR6uSBAp8sTFZUllFMTxWuu43n_-RNsk7w_USTmkoWM/edit
