### ISSUE TITLE
[HPC-AI] [Climate_CFD] Execution fails with latest container on A100

### ISSUE THREAD

**Issue by bharatk-parallel** [gpuhackathons-org/gpubootcamp#19]
The current version of Climate and CFD containers derive from nvcr.io/nvidia/tensorflow:20.01-tf2-py3
These containers won't run on the latest architectures like A100.  In order to run them, we need to use: tf-21.04-tf2-py3 

When the container is derived from tf-21.04-tf2-py3 some python code breaks like serialization error wrt weight files due to the usage of API like tf.keras.models.load_model. Instead, API like load_weights  should be used.

The request is to upgrade the labs to use the latest container supporting A100 and fix the old TF API problems.

**Comment by aswinkumar1999** [comment]
Added support in #28 

Closing issue
