### ISSUE TITLE
Tensorflow Random Seed set for reproducibility 

### ISSUE THREAD

**Issue by badger-lord** [gpuhackathons-org/gpubootcamp#21]
Working with the AI Bootcamp and some of the teams are asking why the randomization happens with the TensorFlow work. 

Could we add tensorflow.random.set_seed() into the notebooks? The numpy random seed does not hold the tensorflow works accountable. Thanks!

[https://www.tensorflow.org/api_docs/python/tf/random/set_seed](url)

**Comment by aswinkumar1999** [comment]
Fixed in #28 

Closing issue
