### ISSUE TITLE
[General] [Misc] Jupyter Template for contribution

### ISSUE THREAD

**Issue by bharatk-parallel** [gpuhackathons-org/gpubootcamp#25]
The request is to enhance the current Jupyter notebook template with more details related to:
-- Structure
-- Flow
-- AI-specific changes if any

**Comment by mozhgan-kch** [comment]
Moving to the "restructuring" milestone to ensure it is in line with the restructuring process.

**Comment by mozhgan-kch** [comment]
Pull request #67 merged.
