### ISSUE TITLE
[General][All] Add Description for all notebooks

### ISSUE THREAD

**Issue by aswinkumar1999** [gpuhackathons-org/gpubootcamp#54]
In every notebook, we need to give a brief of our repository so anyone going through any lab would know the contents of our repository and can explore the materials. We also need to provide relevant references so that anyone interested will become aware of our **Hackathons**.  

For example, at the end of this [Notebook](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/distributed_training.ipynb) 

I found the following lines with relevant hyperlinks. 

> Examples and tutorials
> Here are some examples for using distribution strategy with custom training loops:
> 
> 1. Tutorial to train MNIST using MirroredStrategy.
> 2. Guide on training MNIST using TPUStrategy.
> 3. TensorFlow Model Garden repository containing collections of state-of-the-art models implemented using various strategies.

Which made me curious to check out their repository and the collection of models they have. 

So if we can add a couple of lines about what we do in our repository and hackathons, more people would be aware of our work and interested people could contact us.

**Comment by bharatk-parallel** [comment]
https://github.com/gpuhackathons-org/gpubootcamp/pull/62
