### ISSUE TITLE
[HPC][Nways] Update Nways-Python containers

### ISSUE THREAD

**Issue by mozhgan-kch** [gpuhackathons-org/gpubootcamp#81]
Nways-Python (both the challenge and the base) containers (singularity and docker) are based on **cuda:11.2** container. There is also installations of `nsight-systems-2020.5.1 `and `nsight-compute-2020.2.1 `inside it. These are very old and should be removed.

Nways Fortran and C are up to date. **CUDA 11.2** [1] does have Nsight systems (2021.3) and Compute (2021.2). I suggest testing and using those instead.

[1]. https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

**Comment by programmah** [comment]
This issue has been addressed in #92
